# Makefile

# Compiler
CXX = g++

# Compiler flags
CXXFLAGS = -std=c++11

# Target executable
TARGET = my_program

# Source files
SOURCES = main.cpp

all: $(TARGET)

$(TARGET): $(SOURCES)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SOURCES)
rule2: 
	gcc -o hello hello.c
clean2:
	rm -rf hello
clean:
	rm -f $(TARGET)